#' Tests for get_frugal_metrics()
#'
#' This test file covers the `get_frugal_metrics()` function with mocked
#' dependencies to ensure CRAN compliance (no external downloads, deterministic
#' results, fast execution). All external calls are stubbed with mockery.

# ---- Test fixtures and mock helpers ----

#' Create a minimal temporary package tarball for testing
#'
#' @return Character path to the tarball
create_test_tarball <- function() {
  pkg_dir <- file.path(tempdir(), "testpkg-1.0.0")
  dir.create(pkg_dir, showWarnings = FALSE, recursive = TRUE)
  
  # Create minimal DESCRIPTION file
  writeLines(c(
    "Package: testpkg",
    "Version: 1.0.0",
    "Title: Test Package",
    "Authors@R: person('Test', 'Author', email = 'test@example.com', role = 'aut')",
    "License: GPL (>= 2)",
    "Description: A test package.",
    "Imports: base"
  ), file.path(pkg_dir, "DESCRIPTION"))
  
  # Create a minimal R script
  dir.create(file.path(pkg_dir, "R"), showWarnings = FALSE)
  writeLines(c(
    "#' Test Function",
    "#' @export",
    "test_func <- function() { 42 }"
  ), file.path(pkg_dir, "R", "test.R"))
  
  # Create a minimal man file
  dir.create(file.path(pkg_dir, "man"), showWarnings = FALSE)
  writeLines(c(
    "% Generated by roxygen2: do not edit by hand",
    "\\name{test_func}",
    "\\alias{test_func}",
    "\\title{Test Function}",
    "\\description{A test function}",
    "\\usage{test_func()}",
    "\\value{The answer, 42}"
  ), file.path(pkg_dir, "man", "test_func.Rd"))
  
  # Create tarball
  tar_file <- tempfile(fileext = ".tar.gz")
  old_wd <- getwd()
  on.exit(setwd(old_wd), add = TRUE)
  setwd(tempdir())
  utils::tar(tar_file, files = "testpkg-1.0.0", tar = "internal")
  
  tar_file
}

#' Mock output for get_package_tarfile
#'
#' @param package_name Character package name
#' @param version Character version or NA
#' @param repos Character repos vector
#'
#' @return Character path to tarball (or NULL on error)
mock_get_package_tarfile <- function(package_name, version = NA, repos = getOption("repos")) {
  create_test_tarball()
}

#' Mock output for modify_description_file
#'
#' @param tar_file Character path to tarball
#'
#' @return Character path to modified tarball
mock_modify_description_file <- function(tar_file) {
  # In real function, this modifies the tarball; for tests, return as-is
  tar_file
}

#' Mock output for set_up_pkg
#'
#' @param tar_file Character path to tarball
#' @param check_type Character check type
#'
#' @return List with setup results
mock_set_up_pkg <- function(tar_file, check_type = "1") {
  list(
    package_installed = TRUE,
    pkg_source_path = "/tmp/testpkg-1.0.0",
    build_vignettes = TRUE,
    rcmdcheck_args = list(
      args = "--no-tests",
      path = "/tmp/testpkg-1.0.0",
      quiet = TRUE
    )
  )
}

#' Mock output for install_package_local
#'
#' @param pkg_source_path Character path to package source
#'
#' @return Logical TRUE on success
mock_install_package_local <- function(pkg_source_path) {
  TRUE
}

#' Mock output for get_pkg_desc
#'
#' @param pkg_source_path Character path to package
#' @param fields Character vector of fields to extract
#'
#' @return List of DESCRIPTION fields
mock_get_pkg_desc <- function(pkg_source_path, fields = NULL) {
  list(
    Package = "testpkg",
    Version = "1.0.0",
    Title = "Test Package",
    Author = "Test Author",
    License = "GPL (>= 2)"
  )[if (!is.null(fields)) fields else 1:5]
}

#' Mock output for get_risk_metadata
#'
#' @param executor Character executor name
#'
#' @return List of metadata
mock_get_risk_metadata <- function(executor = NULL) {
  list(
    datetime = "2025-06-12 10:30:00",
    executor = executor %||% Sys.getenv("USER", "test_user"),
    info = list(sys = Sys.info())
  )
}

#' Mock output for create_empty_results
#'
#' @param pkg_name Character package name
#' @param pkg_ver Character package version
#' @param pkg_source_path Character path to package
#' @param metadata List of metadata
#'
#' @return List with empty result slots
mock_create_empty_results <- function(pkg_name, pkg_ver, pkg_source_path, metadata) {
  list(
    pkg_name = pkg_name,
    pkg_version = pkg_ver,
    pkg_source_path = pkg_source_path,
    datetime = metadata$datetime,
    executor = metadata$executor,
    has_bug_reports_url = NA_real_,
    license = NA_character_,
    has_examples = NA_real_,
    has_docs = NA_real_,
    has_ex_docs_score = NA_real_,
    has_maintainer = NA_real_,
    size_codebase = NA_real_,
    has_news = NA_real_,
    has_source_control = NA_real_,
    has_vignettes = NA_real_,
    has_website = NA_real_,
    news_current = NA_real_,
    export_help = NA_real_,
    export_calc = NA_real_,
    check = NA_real_,
    covr = NA_real_,
    dependencies = data.frame(package = character(), type = character()),
    suggested_deps = data.frame(source = character(), suggested_function = character()),
    rev_deps = NA_real_,
    host = list(),
    github_data = list(),
    download = list(),
    version_info = list()
  )
}

#' Mock output for doc_riskmetric
#'
#' @param pkg_name Character package name
#' @param pkg_ver Character package version
#' @param pkg_source_path Character path to package
#'
#' @return List of documentation metrics
mock_doc_riskmetric <- function(pkg_name, pkg_ver, pkg_source_path) {
  list(
    has_bug_reports_url = 0,
    license = 1,
    has_examples = 1,
    has_docs = 1,
    has_ex_docs_score = 1,
    has_maintainer = 1,
    size_codebase = 0.5,
    has_news = 0,
    has_source_control = 1,
    has_vignettes = 0,
    has_website = 0,
    news_current = 0,
    export_help = 0.8
  )
}

#' Mock output for run_rcmdcheck
#'
#' @param pkg_source_path Character path to package
#' @param rcmdcheck_args List of arguments
#'
#' @return List with check results
mock_run_rcmdcheck <- function(pkg_source_path, rcmdcheck_args) {
  list(
    check_score = 0.95,
    res_check = list(
      notes = character(0),
      warnings = character(0),
      errors = character(0)
    )
  )
}

#' Mock output for assess_exports
#'
#' @param pkg_source_path Character path to package
#'
#' @return Numeric export score
mock_assess_exports <- function(pkg_source_path) {
  0.75
}

#' Mock output for get_dependencies
#'
#' @param pkg_source_path Character path to package
#'
#' @return Data frame with dependencies
mock_get_dependencies <- function(pkg_source_path) {
  data.frame(
    type = c("Imports", "Suggests"),
    package = c("base", "testthat"),
    stringsAsFactors = FALSE
  )
}

#' Mock output for get_session_dependencies
#'
#' @param deps Data frame of dependencies
#'
#' @return Numeric dependency score
mock_get_session_dependencies <- function(deps) {
  0.9
}

#' Mock output for get_pkg_author
#'
#' @param pkg_name Character package name
#' @param pkg_source_path Character path to package
#'
#' @return Character author string
mock_get_pkg_author <- function(pkg_name, pkg_source_path) {
  "Test Author <test@example.com>"
}

#' Mock output for extract_license_from_description
#'
#' @param pkg_source_path Character path to package
#'
#' @return Character license name
mock_extract_license_from_description <- function(pkg_source_path) {
  "GPL (>= 2)"
}

#' Mock output for create_traceability_matrix
#'
#' @param pkg_name Character package name
#' @param pkg_source_path Character path to package
#' @param func_covr List coverage data (NULL in frugal mode)
#' @param execute_coverage Logical whether to compute coverage
#'
#' @return List with traceability matrix
mock_create_traceability_matrix <- function(pkg_name, pkg_source_path, func_covr = NULL, execute_coverage = FALSE) {
  list(
    matrix_data = data.frame(
      function_name = "test_func",
      documented = TRUE,
      tested = FALSE
    ),
    coverage = 0
  )
}

#' Mock output for get_risk_analysis
#'
#' @param results List of results
#'
#' @return List with risk analysis
mock_get_risk_analysis <- function(results) {
  list(
    overall_risk = "medium",
    risk_levels = list(
      documentation = "low",
      testing = "high",
      dependencies = "low"
    )
  )
}

# ---- End test fixtures ----

# ---- Tests ----

test_that("get_frugal_metrics returns proper list structure on success", {
  # Setup mocks
  mockery::stub(get_frugal_metrics, "get_package_tarfile", mock_get_package_tarfile)
  mockery::stub(get_frugal_metrics, "modify_description_file", mock_modify_description_file)
  mockery::stub(get_frugal_metrics, "set_up_pkg", mock_set_up_pkg)
  mockery::stub(get_frugal_metrics, "install_package_local", mock_install_package_local)
  mockery::stub(get_frugal_metrics, "get_pkg_desc", mock_get_pkg_desc)
  mockery::stub(get_frugal_metrics, "get_risk_metadata", mock_get_risk_metadata)
  mockery::stub(get_frugal_metrics, "create_empty_results", mock_create_empty_results)
  mockery::stub(get_frugal_metrics, "doc_riskmetric", mock_doc_riskmetric)
  mockery::stub(get_frugal_metrics, "run_rcmdcheck", mock_run_rcmdcheck)
  mockery::stub(get_frugal_metrics, "assess_exports", mock_assess_exports)
  mockery::stub(get_frugal_metrics, "get_dependencies", mock_get_dependencies)
  mockery::stub(get_frugal_metrics, "risk.assessr::get_session_dependencies", mock_get_session_dependencies)
  mockery::stub(get_frugal_metrics, "get_pkg_author", mock_get_pkg_author)
  mockery::stub(get_frugal_metrics, "extract_license_from_description", mock_extract_license_from_description)
  mockery::stub(get_frugal_metrics, "create_traceability_matrix", mock_create_traceability_matrix)
  mockery::stub(get_frugal_metrics, "init_frugal_results", function(x) x)
  mockery::stub(get_frugal_metrics, "init_frugal_covr_list", function() list(total_cov = 0))
  mockery::stub(get_frugal_metrics, "get_risk_analysis", mock_get_risk_analysis)
  
  result <- get_frugal_metrics("testpkg", version = "1.0.0")
  
  # Check top-level structure
  expect_type(result, "list")
  expect_named(result, c("results", "covr_list", "tm_list", "check_list", "risk_analysis"))
})

test_that("get_frugal_metrics returns NULL when tarball fetch fails", {
  mock_error_tarfile <- function(...) {
    stop("Failed to download")
  }
  
  mockery::stub(get_frugal_metrics, "get_package_tarfile", mock_error_tarfile)
  
  expect_warning(
    result <- get_frugal_metrics("nonexistent_package"),
    "Failed to download package"
  )
  expect_null(result)
})

test_that("get_frugal_metrics returns NULL when package unpacking fails", {
  mock_failed_setup <- function(...) {
    list(
      package_installed = FALSE,
      pkg_source_path = NULL,
      rcmdcheck_args = list()
    )
  }
  
  mockery::stub(get_frugal_metrics, "get_package_tarfile", mock_get_package_tarfile)
  mockery::stub(get_frugal_metrics, "modify_description_file", mock_modify_description_file)
  mockery::stub(get_frugal_metrics, "set_up_pkg", mock_failed_setup)
  
  result <- get_frugal_metrics("testpkg")
  expect_null(result)
})

test_that("get_frugal_metrics returns list with NULL results when package installation fails", {
  # When install_package_local returns FALSE, results will be NULL but structure is returned
  mock_failed_install <- function(...) FALSE
  
  mockery::stub(get_frugal_metrics, "get_package_tarfile", mock_get_package_tarfile)
  mockery::stub(get_frugal_metrics, "modify_description_file", mock_modify_description_file)
  mockery::stub(get_frugal_metrics, "set_up_pkg", mock_set_up_pkg)
  mockery::stub(get_frugal_metrics, "install_package_local", mock_failed_install)
  
  result <- get_frugal_metrics("testpkg")
  
  # When installation fails, the function returns a list structure with results=NULL
  expect_type(result, "list")
  expect_named(result, c("results", "covr_list", "tm_list", "check_list", "risk_analysis"))
  expect_null(result$results)
  expect_null(result$check_list)
})

test_that("get_frugal_metrics skips coverage computation in frugal mode", {
  # Track whether get_session_dependencies (related to coverage) was called appropriately
  capture_tm_call <- FALSE
  mock_tm_wrapper <- function(pkg_name, pkg_source_path, func_covr = NULL, execute_coverage = FALSE) {
    capture_tm_call <<- (is.null(func_covr) && !execute_coverage)
    mock_create_traceability_matrix(pkg_name, pkg_source_path, func_covr, execute_coverage)
  }
  
  mockery::stub(get_frugal_metrics, "get_package_tarfile", mock_get_package_tarfile)
  mockery::stub(get_frugal_metrics, "modify_description_file", mock_modify_description_file)
  mockery::stub(get_frugal_metrics, "set_up_pkg", mock_set_up_pkg)
  mockery::stub(get_frugal_metrics, "install_package_local", mock_install_package_local)
  mockery::stub(get_frugal_metrics, "get_pkg_desc", mock_get_pkg_desc)
  mockery::stub(get_frugal_metrics, "get_risk_metadata", mock_get_risk_metadata)
  mockery::stub(get_frugal_metrics, "create_empty_results", mock_create_empty_results)
  mockery::stub(get_frugal_metrics, "doc_riskmetric", mock_doc_riskmetric)
  mockery::stub(get_frugal_metrics, "run_rcmdcheck", mock_run_rcmdcheck)
  mockery::stub(get_frugal_metrics, "assess_exports", mock_assess_exports)
  mockery::stub(get_frugal_metrics, "get_dependencies", mock_get_dependencies)
  mockery::stub(get_frugal_metrics, "risk.assessr::get_session_dependencies", mock_get_session_dependencies)
  mockery::stub(get_frugal_metrics, "get_pkg_author", mock_get_pkg_author)
  mockery::stub(get_frugal_metrics, "extract_license_from_description", mock_extract_license_from_description)
  mockery::stub(get_frugal_metrics, "create_traceability_matrix", mock_tm_wrapper)
  mockery::stub(get_frugal_metrics, "init_frugal_results", function(x) x)
  mockery::stub(get_frugal_metrics, "init_frugal_covr_list", function() list(total_cov = 0))
  mockery::stub(get_frugal_metrics, "get_risk_analysis", mock_get_risk_analysis)
  
  result <- get_frugal_metrics("testpkg")
  
  # Verify traceability matrix was called with execute_coverage=FALSE (frugal mode)
  expect_true(capture_tm_call)
})

test_that("get_frugal_metrics validates package_name input - empty string", {
  expect_error(
    get_frugal_metrics(""),
    "All elements must have at least 1 characters"
  )
})

test_that("get_frugal_metrics validates package_name input - NULL", {
  expect_error(
    get_frugal_metrics(NULL),
    "Must be of type 'string', not 'NULL'"
  )
})

test_that("get_frugal_metrics handles version parameter correctly", {
  # Mock to capture the version passed to get_package_tarfile
  captured_args <- list()
  mock_capture <- function(package_name, version = NA, repos = getOption("repos")) {
    captured_args$version <<- version
    create_test_tarball()
  }
  
  mockery::stub(get_frugal_metrics, "get_package_tarfile", mock_capture)
  mockery::stub(get_frugal_metrics, "modify_description_file", mock_modify_description_file)
  mockery::stub(get_frugal_metrics, "set_up_pkg", mock_set_up_pkg)
  mockery::stub(get_frugal_metrics, "install_package_local", mock_install_package_local)
  mockery::stub(get_frugal_metrics, "get_pkg_desc", mock_get_pkg_desc)
  mockery::stub(get_frugal_metrics, "get_risk_metadata", mock_get_risk_metadata)
  mockery::stub(get_frugal_metrics, "create_empty_results", mock_create_empty_results)
  mockery::stub(get_frugal_metrics, "doc_riskmetric", mock_doc_riskmetric)
  mockery::stub(get_frugal_metrics, "run_rcmdcheck", mock_run_rcmdcheck)
  mockery::stub(get_frugal_metrics, "assess_exports", mock_assess_exports)
  mockery::stub(get_frugal_metrics, "get_dependencies", mock_get_dependencies)
  mockery::stub(get_frugal_metrics, "risk.assessr::get_session_dependencies", mock_get_session_dependencies)
  mockery::stub(get_frugal_metrics, "get_pkg_author", mock_get_pkg_author)
  mockery::stub(get_frugal_metrics, "extract_license_from_description", mock_extract_license_from_description)
  mockery::stub(get_frugal_metrics, "create_traceability_matrix", mock_create_traceability_matrix)
  mockery::stub(get_frugal_metrics, "init_frugal_results", function(x) x)
  mockery::stub(get_frugal_metrics, "init_frugal_covr_list", function() list(total_cov = 0))
  mockery::stub(get_frugal_metrics, "get_risk_analysis", mock_get_risk_analysis)
  
  result <- get_frugal_metrics("testpkg", version = "2.0.0")
  expect_equal(captured_args$version, "2.0.0")
})

test_that("get_frugal_metrics passes repos option correctly", {
  # Mock to capture the repos passed to get_package_tarfile
  captured_args <- list()
  mock_capture <- function(package_name, version = NA, repos = getOption("repos")) {
    captured_args$repos <<- repos
    create_test_tarball()
  }
  
  custom_repos <- c(CRAN = "https://custom.cran.r-project.org")
  
  mockery::stub(get_frugal_metrics, "get_package_tarfile", mock_capture)
  mockery::stub(get_frugal_metrics, "modify_description_file", mock_modify_description_file)
  mockery::stub(get_frugal_metrics, "set_up_pkg", mock_set_up_pkg)
  mockery::stub(get_frugal_metrics, "install_package_local", mock_install_package_local)
  mockery::stub(get_frugal_metrics, "get_pkg_desc", mock_get_pkg_desc)
  mockery::stub(get_frugal_metrics, "get_risk_metadata", mock_get_risk_metadata)
  mockery::stub(get_frugal_metrics, "create_empty_results", mock_create_empty_results)
  mockery::stub(get_frugal_metrics, "doc_riskmetric", mock_doc_riskmetric)
  mockery::stub(get_frugal_metrics, "run_rcmdcheck", mock_run_rcmdcheck)
  mockery::stub(get_frugal_metrics, "assess_exports", mock_assess_exports)
  mockery::stub(get_frugal_metrics, "get_dependencies", mock_get_dependencies)
  mockery::stub(get_frugal_metrics, "risk.assessr::get_session_dependencies", mock_get_session_dependencies)
  mockery::stub(get_frugal_metrics, "get_pkg_author", mock_get_pkg_author)
  mockery::stub(get_frugal_metrics, "extract_license_from_description", mock_extract_license_from_description)
  mockery::stub(get_frugal_metrics, "create_traceability_matrix", mock_create_traceability_matrix)
  mockery::stub(get_frugal_metrics, "init_frugal_results", function(x) x)
  mockery::stub(get_frugal_metrics, "init_frugal_covr_list", function() list(total_cov = 0))
  mockery::stub(get_frugal_metrics, "get_risk_analysis", mock_get_risk_analysis)
  
  result <- get_frugal_metrics("testpkg", repos = custom_repos)
  expect_equal(captured_args$repos, custom_repos)
})

test_that("get_frugal_metrics populates results with documentation metrics", {
  mockery::stub(get_frugal_metrics, "get_package_tarfile", mock_get_package_tarfile)
  mockery::stub(get_frugal_metrics, "modify_description_file", mock_modify_description_file)
  mockery::stub(get_frugal_metrics, "set_up_pkg", mock_set_up_pkg)
  mockery::stub(get_frugal_metrics, "install_package_local", mock_install_package_local)
  mockery::stub(get_frugal_metrics, "get_pkg_desc", mock_get_pkg_desc)
  mockery::stub(get_frugal_metrics, "get_risk_metadata", mock_get_risk_metadata)
  mockery::stub(get_frugal_metrics, "create_empty_results", mock_create_empty_results)
  mockery::stub(get_frugal_metrics, "doc_riskmetric", mock_doc_riskmetric)
  mockery::stub(get_frugal_metrics, "run_rcmdcheck", mock_run_rcmdcheck)
  mockery::stub(get_frugal_metrics, "assess_exports", mock_assess_exports)
  mockery::stub(get_frugal_metrics, "get_dependencies", mock_get_dependencies)
  mockery::stub(get_frugal_metrics, "risk.assessr::get_session_dependencies", mock_get_session_dependencies)
  mockery::stub(get_frugal_metrics, "get_pkg_author", mock_get_pkg_author)
  mockery::stub(get_frugal_metrics, "extract_license_from_description", mock_extract_license_from_description)
  mockery::stub(get_frugal_metrics, "create_traceability_matrix", mock_create_traceability_matrix)
  mockery::stub(get_frugal_metrics, "init_frugal_results", function(x) x)
  mockery::stub(get_frugal_metrics, "init_frugal_covr_list", function() list(total_cov = 0))
  mockery::stub(get_frugal_metrics, "get_risk_analysis", mock_get_risk_analysis)
  
  result <- get_frugal_metrics("testpkg")
  
  # Check that results contain documentation metrics
  expect_equal(result$results$has_bug_reports_url, 0)
  expect_equal(result$results$license, 1)
  expect_equal(result$results$has_examples, 1)
  expect_equal(result$results$export_calc, 0.75)
})

test_that("get_frugal_metrics populates results with check score", {
  mockery::stub(get_frugal_metrics, "get_package_tarfile", mock_get_package_tarfile)
  mockery::stub(get_frugal_metrics, "modify_description_file", mock_modify_description_file)
  mockery::stub(get_frugal_metrics, "set_up_pkg", mock_set_up_pkg)
  mockery::stub(get_frugal_metrics, "install_package_local", mock_install_package_local)
  mockery::stub(get_frugal_metrics, "get_pkg_desc", mock_get_pkg_desc)
  mockery::stub(get_frugal_metrics, "get_risk_metadata", mock_get_risk_metadata)
  mockery::stub(get_frugal_metrics, "create_empty_results", mock_create_empty_results)
  mockery::stub(get_frugal_metrics, "doc_riskmetric", mock_doc_riskmetric)
  mockery::stub(get_frugal_metrics, "run_rcmdcheck", mock_run_rcmdcheck)
  mockery::stub(get_frugal_metrics, "assess_exports", mock_assess_exports)
  mockery::stub(get_frugal_metrics, "get_dependencies", mock_get_dependencies)
  mockery::stub(get_frugal_metrics, "risk.assessr::get_session_dependencies", mock_get_session_dependencies)
  mockery::stub(get_frugal_metrics, "get_pkg_author", mock_get_pkg_author)
  mockery::stub(get_frugal_metrics, "extract_license_from_description", mock_extract_license_from_description)
  mockery::stub(get_frugal_metrics, "create_traceability_matrix", mock_create_traceability_matrix)
  mockery::stub(get_frugal_metrics, "init_frugal_results", function(x) x)
  mockery::stub(get_frugal_metrics, "init_frugal_covr_list", function() list(total_cov = 0))
  mockery::stub(get_frugal_metrics, "get_risk_analysis", mock_get_risk_analysis)
  
  result <- get_frugal_metrics("testpkg")
  
  # Check that R CMD check result is included
  expect_equal(result$results$check, 0.95)
})

test_that("get_frugal_metrics passes check_type='2' to set_up_pkg (frugal mode)", {
  # Mock to capture the check_type argument
  captured_args <- list()
  mock_capture <- function(tar_file, check_type = "1") {
    captured_args$check_type <<- check_type
    mock_set_up_pkg(tar_file, check_type)
  }
  
  mockery::stub(get_frugal_metrics, "get_package_tarfile", mock_get_package_tarfile)
  mockery::stub(get_frugal_metrics, "modify_description_file", mock_modify_description_file)
  mockery::stub(get_frugal_metrics, "set_up_pkg", mock_capture)
  mockery::stub(get_frugal_metrics, "install_package_local", mock_install_package_local)
  mockery::stub(get_frugal_metrics, "get_pkg_desc", mock_get_pkg_desc)
  mockery::stub(get_frugal_metrics, "get_risk_metadata", mock_get_risk_metadata)
  mockery::stub(get_frugal_metrics, "create_empty_results", mock_create_empty_results)
  mockery::stub(get_frugal_metrics, "doc_riskmetric", mock_doc_riskmetric)
  mockery::stub(get_frugal_metrics, "run_rcmdcheck", mock_run_rcmdcheck)
  mockery::stub(get_frugal_metrics, "assess_exports", mock_assess_exports)
  mockery::stub(get_frugal_metrics, "get_dependencies", mock_get_dependencies)
  mockery::stub(get_frugal_metrics, "risk.assessr::get_session_dependencies", mock_get_session_dependencies)
  mockery::stub(get_frugal_metrics, "get_pkg_author", mock_get_pkg_author)
  mockery::stub(get_frugal_metrics, "extract_license_from_description", mock_extract_license_from_description)
  mockery::stub(get_frugal_metrics, "create_traceability_matrix", mock_create_traceability_matrix)
  mockery::stub(get_frugal_metrics, "init_frugal_results", function(x) x)
  mockery::stub(get_frugal_metrics, "init_frugal_covr_list", function() list(total_cov = 0))
  mockery::stub(get_frugal_metrics, "get_risk_analysis", mock_get_risk_analysis)
  
  result <- get_frugal_metrics("testpkg")
  
  # Verify frugal mode (check_type = "2") was used
  expect_equal(captured_args$check_type, "2")
})

test_that("init_frugal_results fills NULL/NA slots with safe placeholders", {
  results <- list(
    pkg_name = "testpkg",
    pkg_version = "1.0.0",
    tests = NULL,
    covr = NA,
    suggested_deps = NULL,
    rev_deps = NULL,
    host = NULL,
    github_data = NULL,
    download = NULL,
    version_info = NULL
  )
  
  filled <- init_frugal_results(results)
  
  # Check tests placeholder
  expect_type(filled$tests, "list")
  
  # Check covr placeholder (must be numeric 0, not NA)
  expect_equal(filled$covr, 0)
  expect_false(is.na(filled$covr))
  
  # Check suggested_deps placeholder
  expect_s3_class(filled$suggested_deps, "data.frame")
  expect_true(nrow(filled$suggested_deps) > 0)
  
  # Check rev_deps placeholder
  expect_equal(filled$rev_deps, 0)
  
  # Check host placeholder
  expect_type(filled$host, "list")
  expect_true(all(c("cran_links", "bioconductor_links", "github_links") %in% names(filled$host)))
  
  # Check github_data placeholder
  expect_type(filled$github_data, "list")
  expect_true("stars" %in% names(filled$github_data))
  
  # Check download placeholder
  expect_type(filled$download, "list")
  expect_true("total_download" %in% names(filled$download))
  
  # Check version_info placeholder
  expect_type(filled$version_info, "list")
  expect_true("all_versions" %in% names(filled$version_info))
})

test_that("init_frugal_results preserves existing non-blank values", {
  results <- list(
    pkg_name = "testpkg",
    tests = list(test1 = "data"),
    covr = 0.85,
    rev_deps = 5
  )
  
  filled <- init_frugal_results(results)
  
  # Existing values should be preserved
  expect_equal(filled$tests$test1, "data")
  expect_equal(filled$covr, 0.85)
  expect_equal(filled$rev_deps, 5)
})

test_that("init_frugal_covr_list returns placeholder structure", {
  covr_list <- init_frugal_covr_list()
  
  # Check top-level structure
  expect_type(covr_list, "list")
  expect_false(covr_list$multi_framework)
  expect_equal(covr_list$total_cov, 0)
  
  # Check nested structure
  expect_true("res_cov" %in% names(covr_list))
  expect_equal(covr_list$res_cov$coverage$totalcoverage, 0)
  expect_null(covr_list$res_cov$coverage$filecoverage)
})

test_that("get_frugal_metrics cleans up temporary files on success", {
  # Track file creation and deletion
  files_created <- character()
  files_deleted <- character()
  
  mock_get_tar <- function(...) {
    f <- tempfile(fileext = ".tar.gz")
    file.create(f)
    files_created <<- c(files_created, f)
    f
  }
  
  mock_unlink <- function(x) {
    if (file.exists(x)) files_deleted <<- c(files_deleted, x)
    invisible(0)
  }
  
  mockery::stub(get_frugal_metrics, "get_package_tarfile", mock_get_tar)
  mockery::stub(get_frugal_metrics, "modify_description_file", mock_modify_description_file)
  mockery::stub(get_frugal_metrics, "set_up_pkg", mock_set_up_pkg)
  mockery::stub(get_frugal_metrics, "install_package_local", mock_install_package_local)
  mockery::stub(get_frugal_metrics, "get_pkg_desc", mock_get_pkg_desc)
  mockery::stub(get_frugal_metrics, "get_risk_metadata", mock_get_risk_metadata)
  mockery::stub(get_frugal_metrics, "create_empty_results", mock_create_empty_results)
  mockery::stub(get_frugal_metrics, "doc_riskmetric", mock_doc_riskmetric)
  mockery::stub(get_frugal_metrics, "run_rcmdcheck", mock_run_rcmdcheck)
  mockery::stub(get_frugal_metrics, "assess_exports", mock_assess_exports)
  mockery::stub(get_frugal_metrics, "get_dependencies", mock_get_dependencies)
  mockery::stub(get_frugal_metrics, "risk.assessr::get_session_dependencies", mock_get_session_dependencies)
  mockery::stub(get_frugal_metrics, "get_pkg_author", mock_get_pkg_author)
  mockery::stub(get_frugal_metrics, "extract_license_from_description", mock_extract_license_from_description)
  mockery::stub(get_frugal_metrics, "create_traceability_matrix", mock_create_traceability_matrix)
  mockery::stub(get_frugal_metrics, "init_frugal_results", function(x) x)
  mockery::stub(get_frugal_metrics, "init_frugal_covr_list", function() list(total_cov = 0))
  mockery::stub(get_frugal_metrics, "get_risk_analysis", mock_get_risk_analysis)
  mockery::stub(get_frugal_metrics, "unlink", mock_unlink)
  
  result <- get_frugal_metrics("testpkg")
  
  # Verify result is not NULL (success path)
  expect_type(result, "list")
})

